### DISCUSSION TITLE
PHP getting started (with Docker)

### DISCUSSION THREAD

**Discussion by Tessmore** [Tessmore/tessmore#31] [PHP]
* Download Docker Desktop [official Docker website](https://www.docker.com/products/docker-desktop).

## Setup

Choose any of the "setups"

* Run server:
      
```bash
docker-compose up -d
```

* Stop server:

```bash
docker-compose down
```

## PHP with apache

Simple `docker-compose.yml`:

```yaml
services:
  php:
    image: php:7.4-apache
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
```

## Wordpress + Caddy

Link: https://github.com/svenakela/caddy-based-wordpress/tree/caddy-community-wiki-example

```bash
git clone git@github.com:svenakela/caddy-based-wordpress.git
```

1. Update `conf/` entries
1. Run `docker-compose up -d` to installcontainers and run them
1. Visit [https://localhost:80](https://localhost:80)
  - The first time you visit a WP it will prompt for the admin account 
  - Save the password (1Password / Keepass)
